# Generated by Django 4.1.7 on 2023-05-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
